config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]
  resources :routes
  resources :stations do
    patch 'update_station_connections'
  end
  resources :carriages, except: [:edit] do
    get 'get_carriage'
  end
  resources :trains do
    get 'get_arrival_stations'
  end
  resources :tickets, except: [:show, :edit]


  get 'stations/search/:name', to: 'stations#search_stations', as: 'search_stations'
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path routes ("/")
  # root "articles#index"
end

app/models/train.rb
class Train < ApplicationRecord
  before_destroy :destroy_seats

  belongs_to :route, optional: true
  has_many :carriages, dependent: :nullify
  has_many :stops, -> {order(:arrival_time)}, class_name: 'PassingTrain', dependent: :destroy

  def destination
    self.route.name if self.route != nil
  end

  def arrival_time_at(station_id)
    self.stops.find_by(station_id: station_id).arrival_time if self.stops != nil
  end

  def departure_time_at(station_id)
    self.stops.find_by(station_id: station_id).departure_time if self.stops != nil
  end

  def create_stops
    self.route.stations.each do |station|
      PassingTrain.create(train_id: self.id, station_id: station.id)
    end
  end

  private

  def destroy_seats
    self.carriages.each do |carriage|
      carriage.seats.destroy_all
    end
  end

end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :admin_user, except: [:get_arrival_stations]

  def index
    @trains = Train.all.includes(:route, :carriages).paginate(page: params[:page], per_page: 7)
  end

  def show
    @train = Train.find(params[:id])
  end

  def edit
    @train = Train.find(params[:id])
    @carriages = Carriage.where(train_id: nil)
    @routes = Route.all
  end

  def create
    Train.create
    redirect_to trains_path
  end

  def update
    if params[:train].has_key?(:stops)
      @train = TrainStopsManager.new(train_id: params[:id],
                                     stops: params[:train][:stops]).call
    elsif params[:train].has_key?(:route_id)
      @train = TrainRoutesManager.new(train_id: params[:id],
                                      route_id: params[:train][:route_id]).call
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @train = Train.find(params[:id])
    @train.destroy
    redirect_to trains_path
  end

  def get_arrival_stations
    @train = Train.find(params[:train_id])
    @departure_station = Station.find(params[:after])
    @stations = TrainArrivalStationsFinder.new(train: @train,
                                               departure_station: @departure_station).call
    respond_to do |format|
      format.js
    end
  end

  private

  def admin_user
    redirect_to root_path unless current_user_admin?
  end

end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/edit.html.erb
<% provide(:title, "Edit train") %>
<div class="center-container">
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li id="carriage-pill-tab" class="nav-item" role="presentation" style="float: none;">
      <button class="nav-link active" id="pills-carriages-tab" data-bs-toggle="pill" data-bs-target="#pills-carriages" type="button" role="tab" aria-controls="pills-carriages" aria-selected="true">Edit carriages</button>
    </li>
    <li id="route-pill-tab" class="nav-item" role="presentation" style="float: none;">
      <button class="nav-link" id="pills-route-tab" data-bs-toggle="pill" data-bs-target="#pills-route" type="button" role="tab" aria-controls="pills-route" aria-selected="false">Edit route</button>
    </li>
    <% unless @train.route.nil? %>
        <li id="stop-pill-tab" class="nav-item" role="presentation" style="float: none;">
          <button class="nav-link" id="pills-stops-tab" data-bs-toggle="pill" data-bs-target="#pills-stops" type="button" role="tab" aria-controls="pills-stops" aria-selected="false">Edit stops</button>
        </li>
    <% end %>
  </ul>
  <div class="tab-content" id="pills-tabContent">
        <div id="pills-carriages" class="tab-pane fade show active" style="margin-top: 30px">
          <ul id="train-carriages-list" style="list-style: none" >
            <% @train.carriages.each do |carriage| %>
              <li id="carriage-<%=carriage.id%>">
                <i class='bi bi-circle-fill blue'></i>
                <a href='<%= carriage_path(carriage.id) %>' style="text-decoration: none"><%= carriage.name %></a></li>
            <% end %>
          </ul>

          <div class="add-station-container" style="margin-top: 2px" data-bs-toggle="modal" data-bs-target="#add_carriage_modal">
            <button class="btn btn-link">
              <span><i class="bi bi-plus-circle"></i></span>
            </button>
            Add new carriage
          </div>
        </div>
        <div id="pills-route" class="tab-pane fade">
          <span class="route-name-span">
            <% if @train.route.nil? %>
              Route <strong>is not set</strong>
            <% else %>
              Route: <strong><%= @train.destination %></strong>
            <% end %>
          </span>
          <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#pick_route_modal"
                  style="font-size: 15px; display: block; margin: 0 auto">
            Pick route
          </button>
        </div>
    <% unless @train.route.nil? %>
        <div id="pills-stops" class="tab-pane fade">
            <ul class="train-stops-ul">
              <% if @train.stops.count == 0 %>
                <% @train.route.stations.each do |station| %>
                  <%= render partial: 'trains/partials/station', locals: { station: station} %>
                <% end %>
              <% else %>
                <% @train.stops.each do |stop| %>
                  <%= render partial: 'trains/partials/stop', locals: { stop: stop} %>
                <% end %>
              <% end %>
            </ul>
          <button class="btn btn-danger" id="errors_examples_btn"
                  style="font-size: 15px; display: none; margin: 10px auto" data-bs-toggle="modal" data-bs-target="#errors_examples_modal">
            Errors examples
          </button>
            <button class="btn btn-success" onclick="validate()"
              style="font-size: 15px; display: block; margin: 0 auto">
              Update
            </button>
        </div>
    <% end %>
  </div>
</div>

<%= render partial: 'trains/partials/carriage_pick_modal', :locals => { :carriages => @carriages} %>
<%= render partial: 'trains/partials/route_pick_modal', :locals => { :routes => @routes} %>
<%= render partial: 'trains/partials/errors_examples_modal' %>

<%= javascript_include_tag "train/edit_carriages" %>
<%= javascript_include_tag "train/edit_route" %>
<%= javascript_include_tag "train/edit_stops" %>

<script>
    const stops = []
    let newCarriage=""
    let carriageOffsetIndex="carriage-".length
    var route = ""

    window.onload = function()
    {   $.ajaxSetup({
          headers: {
              'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
          }
        });
        let query = document.querySelector("#train-carriages-list")
        if (query !== null)
        {
            let lastListItem = document.querySelector("#train-carriages-list").lastElementChild
            lastListItem.innerHTML += '<button id="carriage_remove_button" '
              + 'class="btn" '
              + 'style="font-size: 12px; color: red; margin-left: 20px" '
              + 'value="' + lastListItem.id.substring(carriageOffsetIndex) + '" onClick=removeCarriage(event)>'
              + '<i class="bi bi-x-circle"></i></button>'
        }

    }


    function addRoute()
    {
        if (route !== "")
        {
            $.ajax({
                method: 'PATCH',
                url: '/trains/' + <%= @train.id %>,
                data: { train: { route_id: route }
                }
            })
        }
    }

    function removeCarriage(event)
    {
        let to_remove = event.target.tagName === 'I' ? event.target.parentNode.value : event.target.value
        $.ajax(
          {
              method: 'PATCH',
              url: '/carriages/' + to_remove,
              data: { "train_id": "<%=@train.id %>",
                  carriage: {train_id: "", order_number: "" }}
          }
        )
    }

    function addCarriage()
    {
        if (newCarriage !== "")
        {
            let next_order_number = document.querySelector('#train-carriages-list').childElementCount
            $.ajax
            (
              {
                  method: 'PATCH',
                  url: '/carriages/' + newCarriage,
                  data: {
                      "train_id": "<%=@train.id %>" ,
                      carriage: {train_id: <%=@train.id %>, order_number: next_order_number+1}
                  }
              }
            )
        }
    }


    function updateStops(stops)
    {
        $.ajax(
          {
              method: 'PATCH',
              url: '/trains/' + <%= @train.id %>,
              data: { train: { stops: stops } }
          }
        )
    }

</script>

app/views/trains/get_arrival_stations.js.erb
var stationsUl = document.querySelector('#station-ul')
var list =  '<% if @stations.any? %>'
          + '<% @stations.each do |station| %>'
          + ' <li><a class="stations_to_choose" id="station-<%=station.station_id%>" onclick="stationClick(this.id)" '
          + ' data-chosen="<%=false%>"><%=station.station.name %> (Arrival time: <%= station.arrival_time.strftime("%d.%m.%Y, %H:%M") %>)</a></li>'
          + '<% end %>'
          + '<% else %>'
          + ' <li><a>No stations to choose (seems like starting point is the last station of route)</a></li>'
          + '<% end %>'

stationsUl.innerHTML = list
var modalFooter = document.querySelector('.modal-footer')
var form = document.querySelector('form#confirm-choice-form')
if (form!==null)
{
    form.remove()
}
else
{
    modalFooter.querySelector('#confirm-choice-btn').remove()
}

modalFooter.innerHTML += '<%=button_to "Confirm choice",
                          new_ticket_path, method: :get,
                          class: "btn btn-primary",
                          id: "confirm-choice-btn",
                          form: { id: "confirm-choice-form"},
                          params: { train_id: @train.id, departure_station_id: @departure_station.id, arrival_station_id: "" },
                          disabled: true %>'

app/views/trains/index.html.erb
<% provide(:title, "Trains") %>
<%= button_to "Create new train", trains_path, method: :post, class: "btn btn-outline-success", style: "font-size: 15px; margin: 10px 0" %>
<div class="output-table">
  <table class="table table-hover">
    <thead class="table-dark">
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Number of carriages</th>
      <th>Route</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'trains/partials/train_row', :collection => @trains, :as => :train  %>
    </tbody>
    <%= will_paginate %>
  </table>
</div>

app/views/trains/show.html.erb
<% provide(:title, "Show train") %>
<div class="center-container">
  <ul id="train-carriages-list" style="list-style: none" >
    <% @train.carriages.each do |carriage| %>
      <li id="carriage-<%=carriage.id%>">
        <i class='bi bi-circle-fill blue'></i>
        <a href='<%= carriage_path(carriage.id) %>' style="text-decoration: none"><%= carriage.name %></a> (<%= carriage.seats.where(is_taken: false).count %> seats left)</li>
    <% end %>
  </ul>
</div>

app/views/trains/update.js.erb
// Tabs
var pillsTab = document.querySelector('#pills-tab')
if (pillsTab.querySelector('#stop-pill-tab')===null)
{
    pillsTab.innerHTML += '<li id="stop-pill-tab" class="nav-item" role="presentation" style="float: none;">'
                       +   '<button class="nav-link" id="pills-stops-tab" data-bs-toggle="pill" data-bs-target="#pills-stops" type="button" role="tab" aria-controls="pills-stops" aria-selected="false">Edit stops</button>'
                       + '</li>'
}

// Route
var tabContent = document.querySelector('#pills-tabContent')
tabContent.querySelector('#pills-route').innerHTML =  ' <span class="route-name-span">'
                                                   +  ' <% if @train.route.nil? %>'
                                                   +        'Route <strong>is not set</strong>'
                                                   +   '<% else %>'
                                                   +         'Route: <strong><%= @train.destination %></strong>'
                                                   +   '<% end %>'
                                                   +   '</span>'
                                                   + '<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#pick_route_modal" '
                                                   + 'style="font-size: 15px; display: block; margin: 0 auto">Pick route</button>'

//Stops
stops.length = 0
var stopsContent =  '<ul class="train-stops-ul">'
  +           '<% if @train.stops.any? %>'
  +            '<% @train.stops.each do |stop| %>'
  +              '<%= escape_javascript(render partial: "trains/partials/stop", locals: { stop: stop}) %>'
  +            '<% end %>'
  +           '<% else %>'
  +            '<% @train.route.stations.each do |station| %>'
  +              '<%= escape_javascript(render partial: "trains/partials/station", locals: { station: station}) %>'
  +            '<% end %>'
  +           '<% end %>'
  +         '</ul>'
  +         '<button class="btn btn-danger" id="errors_examples_btn" style="font-size: 15px; display: none; margin: 10px auto" '
  +         'data-bs-toggle="modal" data-bs-target="#errors_examples_modal"> Errors examples </button>'
  +         '<button class="btn btn-success" onclick="validate()" style="font-size: 15px; display: block; margin: 0 auto">Update</button>'
if (tabContent.querySelector('#pills-stops')===null)
{

    tabContent.innerHTML += '<div id="pills-stops" class="tab-pane fade">'
                         + stopsContent
                         + '</div>'
}
else
{
    tabContent.querySelector('#pills-stops').innerHTML = stopsContent
}