config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]
  resources :routes
  resources :stations do
    patch 'update_station_connections'
  end
  resources :carriages, except: [:edit] do
    get 'get_carriage'
  end
  resources :trains do
    get 'get_arrival_stations'
  end
  resources :tickets, except: [:show, :edit]


  get 'stations/search/:name', to: 'stations#search_stations', as: 'search_stations'
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path routes ("/")
  # root "articles#index"
end

app/models/route.rb
class Route < ApplicationRecord

  has_many :trains, dependent: :nullify
  has_many :station_order_numbers, -> { order(:order_number) }, dependent: :destroy
  has_many :stations, :through => :station_order_numbers

  def name
    "#{self.stations.first.name} - #{self.stations.last.name}"
  end

  def add_station(station_id)
    StationOrderNumber.create(route_id: self.id, station_id: station_id, order_number: self.stations.count+1)
  end

  def remove_station(station_id)
    StationOrderNumber.find_by(route_id: self.id, station_id: station_id).destroy
  end

  def stations_after(station_id)
    Station.where(id: self.station_order_numbers
                          .where("order_number > ?",
                                 self.station_order_numbers
                                     .find_by(station_id: station_id).order_number)
                          .map(&:station_id))
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :admin_user

  def index
    @routes = Route.all.includes(:stations).order(id: :ASC).paginate(page: params[:page], per_page: 7)
  end

  def show
    @route = Route.find(params[:id])
  end

  def new
    @route = Route.new
    @stations = Station.all
  end

  def create
    if params[:station_id].present?
      route = RouteCreator.new(station_id: params[:station_id]).call
      respond_to do |format|
        format.js { render js: "window.location = '#{routes_path}/#{route.id}/edit'"}
      end
    end
  end

  def edit
    @route = Route.find(params[:id])
    @connected_stations = NotCommonStationsFinder.new(stations_a: @route.stations.last.connected_stations,
                                                      stations_b: @route.stations).call
  end

  def update
    @route = Route.find(params[:id])
    RouteStationsManager.new(route: @route,
                             station_id: params[:route][:station_id],
                             action: params[:route][:action]).call
    respond_to do |format|
      if @route.stations.present?
        @stations = NotCommonStationsFinder.new(stations_a: @route.stations.last.connected_stations,
                                                stations_b: @route.stations).call
        format.js
      else
        format.js { render js: "window.location = '#{routes_path}'" }
      end
    end
  end

  def destroy
    @route = Route.find(params[:id])
    @route.destroy
    redirect_to request.referrer
  end

  private

  def admin_user
    redirect_to root_path unless current_user_admin?
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/partials/_route_row.html.erb
<tr class='route-row' id="route-<%= route.id %>">
  <th scope="row"><%=route.id %></th>
  <td>
    <% if route.stations.count > 1 %>
      <%= route.stations.first.name %>   -   <%= route.stations.last.name %>
    <% else %>
      -
    <% end %>
  </td>
  <td style="width: 20%">
    <div style="display: flex; flex-direction: row;">
      <%= button_to edit_route_path(route.id), method: :get, class: 'btn btn-outline-primary' do %>
        <i class="bi bi-pencil-square"></i>
      <% end %>
      <%= button_to route_path(route.id), method: :delete, class: 'btn btn-outline-danger', confirm: 'Are you sure?' do %>
        <i class="bi bi-trash3"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/routes/partials/_station_pick_modal.html.erb
<div class="modal fade" id="add_station_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onClick="cancelHide()"></button>
      </div>
      <div class="modal-body">
        <label>Search for stations: </label>
        <input type="text" id="station-search-input" onkeyup="inputKeyUp()" placeholder="Search...">
        <div><label>Stations:</label></div>

        <div style="display: grid; grid-auto-flow: column;">
          <ul id="station-ul" class="vertical-menu" style="width: 100%;">
            <% if stations.count > 0 %>
              <% stations.each do |station|%>
                <li><a class="stations_to_choose" id="station-<%=station.id%>" onclick="stationClick(this.id)"
                       data-chosen="<%=false%>"><%=station.name %></a></li>
                <% end %>
            <% else %>
                <li><a>No stations to choose.</a></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="station_add_submit" onClick="addStation()">Confirm</button>
      </div>
    </div>
  </div>
</div>