config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]
  resources :routes
  resources :stations do
    patch 'update_station_connections'
  end
  resources :carriages, except: [:edit] do
    get 'get_carriage'
  end
  resources :trains do
    get 'get_arrival_stations'
  end
  resources :tickets, except: [:show, :edit]


  get 'stations/search/:name', to: 'stations#search_stations', as: 'search_stations'
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path routes ("/")
  # root "articles#index"
end

app/models/train.rb
class Train < ApplicationRecord
  before_destroy :destroy_seats

  belongs_to :route, optional: true
  has_many :carriages, dependent: :nullify
  has_many :stops, -> {order(:arrival_time)}, class_name: 'PassingTrain', dependent: :destroy

  def destination
    self.route.name if self.route != nil
  end

  def arrival_time_at(station_id)
    self.stops.find_by(station_id: station_id).arrival_time if self.stops != nil
  end

  def departure_time_at(station_id)
    self.stops.find_by(station_id: station_id).departure_time if self.stops != nil
  end

  def create_stops
    self.route.stations.each do |station|
      PassingTrain.create(train_id: self.id, station_id: station.id)
    end
  end

  private

  def destroy_seats
    self.carriages.each do |carriage|
      carriage.seats.destroy_all
    end
  end

end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :admin_user, except: [:get_arrival_stations]

  def index
    @trains = Train.all.includes(:route, :carriages).paginate(page: params[:page], per_page: 7)
  end

  def show
    @train = Train.find(params[:id])
  end

  def edit
    @train = Train.find(params[:id])
    @carriages = Carriage.where(train_id: nil)
    @routes = Route.all
  end

  def create
    Train.create
    redirect_to trains_path
  end

  def update
    if params[:train].has_key?(:stops)
      @train = TrainStopsManager.new(train_id: params[:id],
                                     stops: params[:train][:stops]).call
    elsif params[:train].has_key?(:route_id)
      @train = TrainRoutesManager.new(train_id: params[:id],
                                      route_id: params[:train][:route_id]).call
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @train = Train.find(params[:id])
    @train.destroy
    redirect_to trains_path
  end

  def get_arrival_stations
    @train = Train.find(params[:train_id])
    @departure_station = Station.find(params[:after])
    @stations = TrainArrivalStationsFinder.new(train: @train,
                                               departure_station: @departure_station).call
    respond_to do |format|
      format.js
    end
  end

  private

  def admin_user
    redirect_to root_path unless current_user_admin?
  end

end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/partials/_carriage_pick_modal.html.erb
<div class="modal fade" id="add_carriage_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document" style="width: 430px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onClick="cancelHide()"></button>
      </div>
      <div class="modal-body">
        <label>Search for carriages: </label>
        <input type="text" id="carriage-search-input" onkeyup="inputKeyUp(this)" placeholder="Search...">
        <div style="display: grid; grid-auto-flow: column;">
          <ul id="carriage-ul" class="vertical-menu" style="width: 100%">
            <% carriages.each do |carriage| %>
              <li><a id="carriage-<%=carriage.id %>" onclick="carriageClick(this.id)" data-chosen="false"><%= carriage.name %> (Capacity: <%=carriage.capacity %>)</a></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="carriage_add_submit" onclick=addCarriage()>Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/trains/partials/_errors_examples_modal.html.erb
<div class="modal fade" id="errors_examples_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document" style="width: 430px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onClick="cancelHide()"></button>
      </div>
      <div class="modal-body">
          <table class="table table-hover">
            <thead class="table-dark">
              <tr>
                <th>Error</th>
                <th>Definition</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><input type='datetime-local' style="border: none; border-bottom: 1px solid red" disabled></td>
                <td>Entered time is less than current time</td>
              </tr>
              <tr>
                <td><div style="border-left: 3px solid red;
                  display: flex;
                  flex-direction: column;
                  align-content: space-between;
                  padding: 1px 0 0 15px;">
                  <div><input type='datetime-local' style="border: none; font-size: 12px" disabled></div>
                  <div><input type='datetime-local' style="border: none; font-size: 12px" disabled></div>
                </div></td>
                <td style="vertical-align: middle">Departure time is less than arrival time</td>
              </tr>
              <tr>
                <td><i class="bi bi-geo-alt" style="color: red; font-size: 36px"></i><span style="font-size: 26px">Minsk</span></td>
                <td>Train comes on station earlier than departs from the previous</td>
              </tr>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>

app/views/trains/partials/_route_accordion.html.erb
<div class="accordion-item" onClick='accClick(event)'>
  <h2 class="accordion-header" id="heading-<%= route.id %>">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#route-<%= route.id %>" aria-expanded="false" aria-controls="route-<%= route.id %>" style="font-size: 15px">
      <%= route.name %>
    </button>
  </h2>
  <div id="route-<%= route.id %>" class="accordion-collapse collapse" aria-labelledby="heading-<%= route.id %>" data-bs-parent="#routeAccordion">
    <div class="accordion-body" style="font-size: 15px">
      <ul id="route-accordion-ul">
        <% route.stations.each do |station| %>
          <li><i class="bi bi-record-circle-fill" style="color: #4290f5; margin-right: 5px;" ></i><%= station.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/trains/partials/_route_pick_modal.html.erb
<div class="modal fade" id="pick_route_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document" style="width: 430px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onClick="cancelHide()"></button>
      </div>
      <div class="modal-body">
        <label>Search for routes: </label>
        <input type="text" id="route-search-input" onkeyup="inputKeyUpRoute(this)" placeholder="Search...">
        <br>
        <label style="margin-top: 2vh;">Routes: </label>
        <div id="routeAccordion" style="height: 25vh; overflow-y: auto">
          <%= render partial: 'trains/partials/route_accordion', collection: routes, as: :route %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="route_pick_submit" onclick=addRoute()>Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/trains/partials/_station.html.erb
<li id="station-<%= station.id %>" class="train-stop-li">
  <i class="bi bi-geo-alt blue" style="font-size: 36px"></i>
  <div class="stop-station-title"><%= station.name %></div>
  <div class="stop-station-inputs">
    <div>
      Arrival time: <input id="stop-arr-<%= station.id %>" class="arrival-input" type="datetime-local">
    </div>
    <div>
      Departure time: <input id="stop-dep-<%= station.id %>" class="departure-input" type="datetime-local">
    </div>
  </div>
</li>

app/views/trains/partials/_stop.html.erb
<li id="station-<%= stop.station_id %>" class="train-stop-li">
  <i class="bi bi-geo-alt blue" style="font-size: 36px"></i>
  <div class="stop-station-title"><%= stop.station.name %></div>
  <div class="stop-station-inputs">
    <div>
      Arrival time: <input id="stop-arr-<%= stop.station_id %>" value='<%= stop.arrival_time.strftime("%Y-%m-%dT%H:%M") if stop.arrival_time.present? %>' class="arrival-input" type="datetime-local">
    </div>
    <div>
      Departure time: <input id="stop-dep-<%= stop.station_id %>" value='<%= stop.departure_time.strftime("%Y-%m-%dT%H:%M") if stop.departure_time.present? %>' class="departure-input" type="datetime-local">
    </div>
  </div>
</li>

app/views/trains/partials/_train_row.html.erb
<tr class="train-row" id="train-<%= train.id%>">
  <th><%=train.id %></th>
  <td><%=train.name%></td>
  <td><%=train.carriages.count %></td>
  <td>
    <% if !train.route.nil? %>
      <% if train.route.stations.count>1 %>
        <%= train.route.stations.first.name %> - <%= train.route.stations.last.name %>
      <% end %>
    <% else %>
      -
    <% end %>
  </td>
  <td style="width: 20%">
    <div style="display: flex; flex-direction: row">
      <%= button_to edit_train_path(train.id), method: :get, class: 'btn btn-outline-primary' do %>
        <i class="bi bi-pencil-square"></i>
      <% end %>
      <%= button_to train_path(train.id), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } do %>
        <i class="bi bi-trash3"></i>
      <% end %>
    </div>
  </td>
</tr>