config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]
  resources :routes
  resources :stations do
    patch 'update_station_connections'
  end
  resources :carriages, except: [:edit] do
    get 'get_carriage'
  end
  resources :trains do
    get 'get_arrival_stations'
  end
  resources :tickets, except: [:show, :edit]


  get 'stations/search/:name', to: 'stations#search_stations', as: 'search_stations'
  get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path routes ("/")
  # root "articles#index"
end

app/models/station.rb
class Station < ApplicationRecord
  before_destroy :destroy_connections

  has_many :station_connections
  has_many :connected_stations, :through => :station_connections,
           source: :connected_station

  has_many :station_order_numbers, dependent: :destroy
  has_many :routes, :through => :station_order_numbers

  has_many :passing_trains, -> {order(:arrival_time)}, dependent: :destroy

  has_many :arrival_tickets, class_name: 'Ticket', foreign_key: :destination_station_id, dependent: :destroy
  has_many :departure_tickets, class_name: 'Ticket', foreign_key: :departure_station_id, dependent: :destroy

  validates :name, presence: true, length: {maximum: 30, minimum: 1}

  def destroy_connections
    StationConnection.where(station_id: self.id)
                     .or(StationConnection.where(connected_station_id: self.id))
                     .destroy_all
  end

  def self.search(term)
    where("name LIKE :prefix", prefix: "#{term}%")
  end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :admin_user, except: [:show, :index]

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:success]= "You have successfully created station."
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def index
    @stations = Station.search(params[:name]).order(id: :ASC).paginate(page: params[:page], per_page: 7)
  end

  def show
    @station = Station.find(params[:id])
  end

  def edit
    @station = Station.find(params[:id])
    @stations = Station.where.not(id: params[:id])
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(station_params)
      redirect_to stations_path
    else
      render 'edit'
    end
  end

  def update_station_connections
    puts params
    @station = Station.find(params[:station_id])
    StationConnectionsManager.new(station: @station,
                                  station_params: params[:station]).call
    respond_to do |format|
      format.js
    end
  end

  def destroy
    Station.find(params[:id]).destroy
    flash[:success] = 'Station deleted.'
    redirect_to stations_path
  end


  private

  def station_params
    params.require(:station).permit(:name)
  end

  def admin_user
    redirect_to root_path unless current_user_admin?
  end

end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/partials/_edit_station_connections_modal.html.erb
<div class="modal fade" id="edit_station_connections_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onClick="cancelHide()"></button>
      </div>
      <div class="modal-body">
        <label>Search for stations: </label>
        <input type="text" id="station-search-input" onkeyup="inputKeyUp()" placeholder="Search...">
        <div><label>Stations:</label></div>

        <div style="display: grid; grid-auto-flow: column;">
          <ul id="station-ul" class="vertical-menu" style="width: 100%;">
            <% stations.each do |station|%>
              <li><a class="stations_to_choose" id="station-<%=station.id%>" onclick="stationClick(this.id)"
                     data-chosen="<%= concrete_station.connected_stations.include?(station) ? true : false%>"><%=station.name %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="station_connections_add_submit">Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/stations/partials/_station_row.html.erb
<tr class='station-row' id="station-<%= station.id %>" style="height:75px">
  <% if current_user_admin? %>
    <th scope="row"><%=station.id %></th>
  <% end %>
  <td><%= station.name %>  </td>
  <td style="width: 20%">
    <div style="display: flex; flex-direction: row;">
      <% if current_user_admin? %>
        <%= button_to edit_station_path(station.id), method: :get, class: 'btn btn-outline-primary' do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= button_to station_path(station.id), method: :delete, class: 'btn btn-outline-danger', confirm: 'Are you sure?' do %>
           <i class="bi bi-trash3"></i>
        <%end %>
        <% else %>
        <% if station.passing_trains.present?  %>
          <%= button_to station_path(station.id), method: :get, class: 'btn btn-outline-primary' do%>
            Show passing trains <i class="bi bi-search"></i>
          <% end %>
        <%end %>
      <% end %>
    </div>
  </td>
</tr>